name:                hw3
version:             0.1.0.0
github:              "daniil-ushkov/hw3"
license:             BSD3
author:              "Daniil Ushkov"
maintainer:          "daniil.ushkov@yandex.ru"
copyright:           "2022 Daniil Ushkov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/daniil-ushkov/hw3#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- prettyprinter
- prettyprinter-ansi-terminal
- haskeline
- scientific
- transformers
- text
- containers
- bytestring 
- utf8-string
- zlib
- serialise
- directory
- time
- random

library:
  source-dirs: src

executables:
  hw3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw3

tests:
  hw3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw3
    - tasty
    - tasty-hspec
    - tasty-hedgehog
    - hedgehog
